apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-agent
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}-agent
    tier: backend
spec:
  replicas: {{ .Values.agentPod.replicas }}
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-agent
        tier: backend
    spec:
      volumes:
        - name: vault-token
          emptyDir:
            sizeLimit: 1Mi
            medium: Memory
      initContainers:
        - name: vault-retrieve
          image: "{{ .Values.agentVaultRetrieve.image.repository }}:{{ .Values.agentVaultRetrieve.image.tag }}"
          imagePullPolicy: {{ .Values.agentVaultRetrieve.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config-init
            - secretRef:
                name: {{ .Chart.Name }}-agent-secrets
          volumeMounts:
            - name: vault-token
              mountPath: "{{ .Values.agentVaultRetrieve.env.mountPath }}"
      containers:
        - name: {{ .Chart.Name }}-agent
          image: "{{ .Values.agentPod.image.registry }}/{{ .Values.agentPod.image.repository }}:{{ .Values.agentPod.image.tag }}"
          imagePullPolicy: {{ .Values.agentPod.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config-app
          volumeMounts:
            - name: vault-token
              mountPath: "{{ .Values.agentVaultRetrieve.env.mountPath }}"
          resources:
            requests:
              memory: {{ .Values.agentPod.resources.requests.memory }}
              cpu: {{ .Values.agentPod.resources.requests.cpu }}
            limits:
              memory: {{ .Values.agentPod.resources.limits.memory }}
              cpu: {{ .Values.agentPod.resources.limits.cpu }}
          readinessProbe:
            httpGet:
              path: {{ .Values.agentPod.readinessProbe.httpGet.path }}
              port: {{ .Values.agentPod.readinessProbe.httpGet.port }}
            timeoutSeconds: {{ .Values.agentPod.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.agentPod.livenessProbe.httpGet.path }}
              port: {{ .Values.agentPod.livenessProbe.httpGet.port }}
            timeoutSeconds: {{ .Values.agentPod.livenessProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.agentPod.livenessProbe.initialDelaySeconds }}
