apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-init-agent
  namespace: {{ .Release.namespace }}
data:
  VAULT_REQUEST: |{{ .Values.agentVaultRetrieve.env.vaultRequest | nindent 4 }}
  MOUNT_PATH: "{{ .Values.agentVaultRetrieve.env.mountPath }}"
  VAULT_ADDR: "{{ .Values.agentVaultRetrieve.env.vaultUri }}"
