---
server:
  port: 8443
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
    threads:
      max: 64
  servlet:
    session:
      timeout: 600

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: FinancesCP
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 10000
  data:
    redis:
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  kafka:
    bootstrap-servers: kafka.lavacro.net:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3
      client-id: finances-producer
      properties:
        spring.json.trusted.packages: com.lavacro.finances.kafka.model
    template:
      default-topic: finances-topic
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:finances-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: &keycloak-issuer-uri ${KEYCLOAK_ISSUER_URI:https://www.lavacro.com/realms/lavacro}
      resourceserver:
        jwt:
          issuer-uri: *keycloak-issuer-uri
          jws-algorithms:
            - PS256
            - RS256
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      jdbc:
        schema: modulith_events
        schema-initialization:
          enabled: false
