namespace: finances

webapp:
  replicaCount: 2
  image:
    registry: "registry:5000"
    repository: "finances"
    tag: "4.1.0"
    pullPolicy: IfNotPresent

vaultRetrieve:
  image:
    repository: registry:5000/govault
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  env:
    mountPath: "/var/tmp/vault"
    vaultUri: 'http://vault:8201'
    vaultRequest: |
      {
        "vault_request": [{
          "mount": "lavacro",
          "path": "prod/database/postgresql",
          "items": [{
            "key": "password",
            "label": "spring.datasource.password"
          }]
        }],
        "file_path": "/var/tmp/vault/vault.properties"
      }

agentVaultRetrieve:
  image:
    repository: registry:5000/govault
    tag: "1.0.4"
    pullPolicy: IfNotPresent
  env:
    mountPath: "/var/tmp/vault"
    vaultUri: 'http://vault.lavacro.net:8201'
    vaultRequest: |
      {
        "vault_request": [{
          "mount": "lavacro",
          "path": "prod/llm/anthropic",
          "items": [{
            "key": "api_key",
            "label": "anthropic.api.key"
        },{
          "mount": "lavacro",
          "path": "prod/llm/anthropic",
          "items": [{
            "key": "api_key",
            "label": "anthropic.api.key"
        },{
          "mount": "lavacro",
          "path": "prod/llm/gemini",
          "items": [{
            "key": "api_key",
            "label": "gemini.api.key"
        }],
        "file_path": "/var/tmp/vault/vault.properties"
      }
app:
  env:
    profile: home
    propertiesFile: "/var/tmp/vault/vault.properties"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"
      cpu: "500m"
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8443
    timeoutSeconds: 60
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8443
    timeoutSeconds: 3
    initialDelaySeconds: 60

service:
  type: LoadBalancer
  port: 80
  targetPort: 8443

agentPod:
  replicas: 1
  env:
    propertiesFile: "/var/tmp/vault/vault.properties"
  image:
    registry: "registry:5000"
    repository: "finances-agent"
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"
      cpu: "500m"
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    timeoutSeconds: 60
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    timeoutSeconds: 3
    initialDelaySeconds: 60

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: finances.cloud.lavacro.net
    paths:
    - path: "/"
      pathType: Prefix

redis:
  enabled: true
  image:
    repository: redis
    tag: "5.0.6"
  resources:
    requests:
      cpu: "250m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"
  service:
    type: LoadBalancer
    port: 6379

configMap:
  dbUser: "david"
  dbUrl: "jdbc:postgresql://prod-db.lavacro.net:5432/finances"
  profile: "home"
  propertiesFile: "/var/tmp/vault/vault.properties"
